# SVM (Support Vector Machine) 

# Introduction

Suppose you are given plot of two label classes on graph as shown in image (A). Can you decide a separating line for the classes?

![imageA_SVM_theory](https://drive.google.com/uc?id=1e1Ogr7k1o6NhEPhrcLx1miKZ256Jagam 'imageA_SVM_theory')



You might have come up with something similar to following image (image B). It fairly separates the two classes. Any point that is left of line falls into black circle class and on right falls into blue square class. Separation of classes. That’s what SVM does. It finds out a line/ hyper-plane (in multidimensional space that separate outs classes).

![ImageB_SVM_theory](https://drive.google.com/uc?id=13E5agNTM50UajVcA0bYfIziA9DjsmS9H 'ImageB_SVM_theory')

**Making it a Bit complex…**

So far so good. Now consider what if we had data as shown in image below? Clearly, there is no line that can separate the two classes in this x-y plane. So what do we do? We apply transformation and add one more dimension as we call it z-axis. Lets assume value of points on z plane, w = x² + y². In this case we can manipulate it as distance of point from z-origin. 

Now if we plot in z-axis, a clear separation is visible 
and a line can be drawn .

![ImageC_SVM_theory](https://drive.google.com/uc?id=19swJe7sF0XfB6--TLpwO0p0SY5nHWqFw 'ImageC_SVM_theory')

When we transform back this line to original plane, it maps to circular boundary as shown in image E. <b>These transformations are called kernels.</b>

![imageE_SVM_theory](https://drive.google.com/uc?id=1prqqeYGVlfnzsviIuiiowikgK-jyVoLV 'imageE_SVM_theory')

<img src="https://miro.medium.com/max/576/1*7bNCIqw07ZeBhz_s0mhZiA.gif" />

Making it a little more complex…
-----------------------------------------------

What if data plot overlaps? 
Or, 
what in case some of the black points are inside the blue ones? 
Which line among 1 or 2 ? should we draw ?

![ImageE_1_2_SVM_theory](https://drive.google.com/uc?id=1TF5KBoMMXNG-84NwYFS_wN1nXpQmcJec 'ImageE_1_2_SVM_theory')

This is called regularization parameter. 

* In next section, we define two terms regularization parameter and gamma. 

** These are tuning parameters in SVM classifier. Varying those we can achive considerable non linear classification line with more accuracy in reasonable amount of time.

Tuning parameters: Regularization, Gamma and Margin.
--------------------------------------------------------------------------------

Regularization :
---------------------
The Regularization parameter (often termed as C parameter in python’s sklearn library) tells the SVM optimization how much you want to avoid misclassifying each training example.

For large values of C, the optimization will choose a smaller-margin hyperplane if that hyperplane does a better job of getting all the training points classified correctly. Conversely, a very small value of C will cause the optimizer to look for a larger-margin separating hyperplane, even if that hyperplane misclassifies more points.

The images below are example of two different regularization parameter. 
**Left one has some misclassification due to lower regularization value. 
**Higher value leads to results like right one.

![regularization_example_svm_theory](https://drive.google.com/uc?id=1TFGJIF4xNozd1kKN5xK_kjZKOnUI6vD2 'regularization_example_svm_theory')

Gamma
-----------
The gamma parameter defines how far the influence of a single training example reaches, with low values meaning ‘far’ and high values meaning ‘close’. In other words, with low gamma, points far away from plausible seperation line are considered in calculation for the seperation line. Where as high gamma means the points close to plausible line are considered in calculation.


![gamma_svm_theory](https://drive.google.com/uc?id=1MNkHkzFQFxPKTcAIypOEwrUaQt0lQvZo 'gamma_svm_theory')

Margin
----------

A margin is a separation of line to the closest class points.

A good margin is one where this separation is larger for both the classes. Images below gives to visual example of good and bad margin. A good margin allows the points to be in their respective classes without crossing to other class.

![margin_svm_theory](https://drive.google.com/uc?id=1vzCMyWR65XEww5R42zZzERgORifdfHj9 'margin_svm_theory')

# Coding Examples

In [1]:
# doing the minimum necessary imports
# more modules would be imported as and when needed

import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

# reading data from CSV file. 
# reading bank currency note data into pandas dataframe.
bankdata = pd.read_csv("bill_authentication.csv")  

# Exploratory Data Analysis
print(bankdata.shape)  
print("------------")
print(bankdata.head()) 

(1372, 5)
------------
   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0


In [2]:
# Data Preprocessing
# Data preprocessing involves 
# (1) Dividing the data into attributes and labels and 
# (2) dividing the data into training and testing sets.

# To divide the data into attributes and labels, do :
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class']  

# the final preprocessing step is to divide data into training and test sets
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=10)


# Training the Algorithm. Here we would use simple SVM , 
# i.e linear SVM
from sklearn.svm import SVC  

svclassifier = SVC(kernel='linear')  # classifying linear data
# kernel can take many values like
# Gaussian, polynomial, sigmoid, or computable kernel
# default kernel = rbf ( Radial Basis Function)

svclassifier.fit(X_train, y_train)  

# Making Predictions
y_pred = svclassifier.predict(X_test)

# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix  

print(confusion_matrix(y_test,y_pred))  

print(classification_report(y_test,y_pred)) 

# Remember : for evaluating classification-based ML algo use  
# confusion_matrix, classification_report and accuracy_score.
# And for evaluating regression-based ML Algo use Mean Squared Error(MSE), ...

[[151   1]
 [  1 122]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       152
           1       0.99      0.99      0.99       123

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



Note : to understand Precision, recall, f1-score, support; see this post
https://towardsdatascience.com/accuracy-precision-recall-or-f1-331fb37c5cb9

For example : In the above o/p -> (refer confusion matrix)
166/167 bank entries were correctly predicted false.
also, 108/108 bank entries were correctly predicted true.

The total no. of observations are also indicated as support. 
see support values -> for 0(i.e false) it is 167 and for 1(i.e true) it is 108 

further, Precision talks about how precise/accurate your model is ?
Precision tells us, out of those predicted positive, how many of them are actually positive. Our SVM model's precision is 1.00 i.e 100% in predicting the actual Negatives and 99% in predicting the actual positives. 

If anybody wishes to explore the Maths behind the kernels , then look here
https://www.datacamp.com/community/tutorials/svm-classification-scikit-learn-python#kernels

 # Applying SVM over non-linear data
 
In case of non-linearly separable data, the simple SVM algorithm cannot be used. Rather, a modified version of SVM, called Kernel SVM, is used.

Basically, the kernel SVM projects the non-linearly separable data in lower dimensions to linearly separable data in higher dimensions in such a way that data points belonging to different classes are allocated to different dimensions. Again, there is complex mathematics involved in this, but you do not have to worry about it in order to use SVM. Rather we can simply use Python's Scikit-Learn library to implement and use the kernel SVM.

Implementing Kernel SVM with Scikit-Learn is similar to the simple SVM. In this section, we will use the famous iris dataset to predict the category to which a plant belongs based on four attributes: sepal-width, sepal-length, petal-width and petal-length.

We will try all three possible kernels; namely polynomial, Gaussian, and sigmoid kernels. 

In [3]:
import seaborn as sns
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt
from sklearn import svm, datasets

# import some data to play with
irisdata = sns.load_dataset('iris')
irisdata.head()  # have a look at the attributres(=> X) and Labels(=> y)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
# Preprocessing data
X = irisdata.drop('species', axis=1)  
y = irisdata['species']

# Train Test Split
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=10)  

# Training the Algorithm
To train the kernel SVM, we use the same SVC class of the Scikit-Learn's svm library.

We will implement polynomial, Gaussian, and sigmoid kernels to see which one works better for our problem.

# 1. Polynomial Kernel

See this https://slideplayer.com/slide/9163126/27/images/8/Graphs+of+Polynomial+Functions.jpg

In the case of polynomial kernel, you also have to pass a value for the degree parameter of the SVC class. This basically is the degree of the polynomial. Take a look at how we can use a polynomial kernel to implement kernel SVM:

In [4]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='poly', degree=8, gamma='auto')  
# gamma is optional. But it gives a FutureWarning. To avoid it , specify
# gamma as 'auto' or 'scale'

svclassifier.fit(X_train, y_train)

# Making Predictions
# Now once we have trained the algorithm, 
# the next step is to make predictions on the test data.
y_pred = svclassifier.predict(X_test)  


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

# Note : Note the misclassification in 'virginica' species

[[143   9]
 [  1 122]]
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       152
           1       0.93      0.99      0.96       123

    accuracy                           0.96       275
   macro avg       0.96      0.97      0.96       275
weighted avg       0.97      0.96      0.96       275



# 2. Gaussian Kernel

To use Gaussian kernel, you have to specify 'rbf' as value for the Kernel parameter of the SVC class.

In [5]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='rbf', gamma='auto')  
svclassifier.fit(X_train, y_train) 

# Prediction and Evaluation
y_pred = svclassifier.predict(X_test)  

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

# Note : Note the best performance thats 100% precise

[[152   0]
 [  0 123]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       152
           1       1.00      1.00      1.00       123

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



# 3. Sigmoid Kernel
Finally, let's use a sigmoid kernel for implementing Kernel SVM. 
To use the sigmoid kernel, you have to specify 'sigmoid' as value for the kernel parameter of the SVC class.Take a look at the following script:  

In [6]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='sigmoid', gamma='auto')  
svclassifier.fit(X_train, y_train)

# Prediction and Evaluation
y_pred = svclassifier.predict(X_test)  

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

# Note : Note the very poor perfomance from Sigmoid kernel

[[121  31]
 [ 32  91]]
              precision    recall  f1-score   support

           0       0.79      0.80      0.79       152
           1       0.75      0.74      0.74       123

    accuracy                           0.77       275
   macro avg       0.77      0.77      0.77       275
weighted avg       0.77      0.77      0.77       275



# Comparison of Kernel Performance

If we compare the performance of the different types of kernels we can clearly see that the sigmoid kernel performs the worst. This is due to the reason that sigmoid function returns two values, 0 and 1, therefore it is more suitable for binary classification problems. However, in our case we had three output classes.

Amongst the Gaussian kernel and polynomial kernel, we can see that Gaussian kernel achieved a perfect 100% prediction rate while polynomial kernel misclassified three instances. Therefore the Gaussian kernel performed slightly better. However, there is no hard and fast rule as to which kernel performs best in every scenario. It is all about testing all the kernels and selecting the one with the best results on your test dataset.